### ISSUE TITLE
Global Airport Database

### ISSUE THREAD

**Issue by arturaskerelis** [androdev88/FS2024Wormhole#1]
Can you reformat this database via AI and put in into the csv for your app?

[GlobalAirportDatabase.txt](https://github.com/user-attachments/files/18173546/GlobalAirportDatabase.txt)

**Comment by androdev88** [comment]
Try this one, note that locations are not exact runway start at correct altitude so you will have  to use +500 button not to spawn inside ATC :) You also need to replace index.html in stat
ic as the list was too long for browser to handle I've added (AI did) pagination and search to the file.


[locations.zip](https://github.com/user-attachments/files/18173918/locations.zip)

**Comment by arturaskerelis** [comment]
I think removing duplicates, and when theres too many in the list, the app crashes. I think its a website length issue.  Pages would take forever to build, but theres a max list length breaking somewhere

**Comment by arturaskerelis** [comment]
[airports_starting_with_L (1).csv](https://github.com/user-attachments/files/18174081/airports_starting_with_L.1.csv)

Tried that one, only airports starting with L, app starts just fine, but the website wont show the super long list.

**Comment by arturaskerelis** [comment]
holy smokles nice work!

**Comment by arturaskerelis** [comment]
Let me see if I can build a database for you for ICAO, Runway, RWHDG, Lat, Long, RWTDZE ALT, RWHDG.

**Comment by arturaskerelis** [comment]
Can you have a speed checkmark to set the speed as 0?

 teleport = async (location, altitudeOffset = 0) => {
            try {
                await fetch('/api/setCords', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        latitude: location.latitude,
                        longitude: location.longitude,
                        altitude: location.altitude + altitudeOffset
                        
                        
                       https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Misc_Variables.htm?rhhlterm=speed&rhsearch=speed
                       

                       SURFACE RELATIVE GROUND SPEED

**Comment by androdev88** [comment]
it is possible to add, but I consider it minor improvement, you can always make sure to use parking brake before teleport, lets wait and see if we get some official support for teleports first, this project for now is to fill (hopefully temporary) gap of official game not supporting teleport

**Comment by androdev88** [comment]
Airport DB added in 1.1.0
