### ISSUE TITLE
Heading

### ISSUE THREAD

**Issue by arturaskerelis** [androdev88/FS2024Wormhole#2]
Also, if you can add an airplane heading tag, when we teleport, it can be facing down the runway, same heading as when we saved the pin.

**Comment by androdev88** [comment]
I found nearby offset (longitude - 0x18) which coresponds with heading but changing it changes only the camera heading when paused, as soon as it is unpaused the heading follows last one. Also scaned nearby 1MB of RAM for similar values, looks like heading is stored and handled by different part of engine, it might be harder to find it.

**Comment by arturaskerelis** [comment]
Check https://github.com/androdev88/FS2024Wormhole/issues/1#issuecomment-2550249943. Thoughts?

Great for spawning on the ground.  I tested that if I am paused, and spawn on the ground at an airport in the big database, it pops up to the ground without crashing as long as the speed is 0

**Comment by arturaskerelis** [comment]
Called it. Game updated this AM, pointermap broke. Maybe you can do it through SimConnect or FSUIPC?

**Comment by androdev88** [comment]
Read only heading was added in 1.1.0, it also changes plane orientation when paused, it doesn't affect actual plane's heading it will go back once unpaused. There is not plans to support heading as it is stored in different location which would increase work needed to find new pointers when new version of the game is released.
