### ISSUE TITLE
Locations file with Fixes, VORs and NDBs added

### ISSUE THREAD

**Issue by arturaskerelis** [androdev88/FS2024Wormhole#4]
HEre you go, all worldwide fixes, VORs and NDBs.
[locations.csv](https://github.com/user-attachments/files/18215484/locations.csv)

**Comment by arturaskerelis** [comment]
Added a bunch of runway thresholds with headings as well.

**Comment by arturaskerelis** [comment]
https://drive.google.com/file/d/1Zv1Z6c-ta4-MkNDzSNDXkpS6vJzE67jW/view?usp=sharing

**Comment by androdev88** [comment]
looks great, thank you, included in 1.1.1 release
