### ISSUE TITLE
1.2.8.0 - Steam Pointers

### ISSUE THREAD

**Issue by penderes** [androdev88/FS2024Wormhole#5]
Does anybody have the pointers/offsets for Steam version?

I was able to make the tool work with the Steam .exe by adjusting the file size, however I was not able to generate the pointers/offsets with the tutorial provided (and several other pointer-scan tutorials from the internet).

The pointer list comes up empty every time, even if I have the correct addresses in CE. When I compare against the 1.2.7.0 pointerlist and try to update the list to my current address, nothing shows up as well.

**Comment by androdev88** [comment]
What is your game exe file size in bytes ?

**Comment by androdev88** [comment]
try any of 
1.2.8.0-199117312=0x092C8140,0x3A8
1.2.8.0-199117312=0x092C9DE8,0x3A8
1.2.8.0-199117312=0x092C9E28,0x3A8
1.2.8.0-199117312=0x092C9EA8,0x3A8
1.2.8.0-199117312=0x092C9EE8,0x3A8

**Comment by androdev88** [comment]
how does the pointer scan window look when you open 4.PTR when in Career Mode
[4.PTR.results.zip](https://github.com/user-attachments/files/18219933/4.PTR.results.zip)

**Comment by androdev88** [comment]
last one looks correct expand first column to see address is it 0A0E1968 ?

**Comment by androdev88** [comment]
when opening pointer map you can tell which pointers are correct by looking at value in this case it is 0.89.... which is reasonable value for longitude in radians 

Thank you for help with this, I've included Steam pointer in 1.1.1 release.
